#!/usr/bin/env bash
# install.sh – install scphasepapy into a SeisComP environment
#
# Usage:
#   ./install.sh [SEISCOMP_ROOT]
#
# If SEISCOMP_ROOT is not given, the script tries:
#   1. $SEISCOMP_ROOT environment variable
#   2. ~/seiscomp (common default)
#
# After installation:
#   seiscomp enable scphasepapy
#   seiscomp update-config scphasepapy
#   seiscomp start scphasepapy

set -euo pipefail

SC_ROOT="${1:-${SEISCOMP_ROOT:-$HOME/seiscomp}}"
if [[ ! -d "$SC_ROOT" ]]; then
    echo "ERROR: SeisComP root '$SC_ROOT' not found."
    echo "       Pass the path as the first argument: $0 /path/to/seiscomp"
    exit 1
fi
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Using SeisComP root: $SC_ROOT"

echo
echo "==> Installing scphasepapy Python package ..."

if [[ -n "${SC_PYTHON:-}" && -x "$SC_PYTHON" ]]; then
    SC_P="$SC_PYTHON"
    echo "    Using SC_PYTHON env var: $SC_P"
elif [[ -x "$SC_ROOT/bin/seiscomp-python" ]]; then
    SC_P="$SC_ROOT/bin/seiscomp-python"
elif command -v seiscomp-python &>/dev/null; then
    SC_P="$(command -v seiscomp-python)"
else
    SC_P="$(command -v python3)"
    echo "    WARNING: seiscomp-python not found; using $SC_P"
    echo "    If 'import seiscomp' fails, set SC_PYTHON and re-run."
fi
echo "    Python: $SC_P"

if "$SC_P" -m pip --version &>/dev/null; then
    "$SC_P" -m pip install --quiet -e "$SCRIPT_DIR" && \
        echo "    Package installed (editable)" || \
        echo "    WARNING: pip install failed – run manually: $SC_P -m pip install -e $SCRIPT_DIR"
else
    echo "    WARNING: pip not available for $SC_P"
    echo "    Run manually: $SC_P -m pip install -e $SCRIPT_DIR"
fi

echo
echo "==> Installing executable to $SC_ROOT/bin/scphasepapy ..."
BIN_DEST="$SC_ROOT/bin/scphasepapy"
python3 - "$SCRIPT_DIR/lib/scphasepapy/scphasepapy.py" "$BIN_DEST" <<'PYEOF'
import sys
src_path, dst_path = sys.argv[1], sys.argv[2]
with open(src_path) as f:
    lines = f.read().split('\n')
if lines[0].startswith('#!'):
    lines[0] = '#!/usr/bin/env seiscomp-python'
lines.insert(1, '# AUTO-GENERATED by scphasepapy/install.sh – edit source in scphasepapy/lib/scphasepapy/scphasepapy.py')
with open(dst_path, 'w') as f:
    f.write('\n'.join(lines))
print(f'Written {dst_path}')
PYEOF
chmod 755 "$BIN_DEST"
echo "    Installed $BIN_DEST"

echo
echo "==> Installing module description ..."
DESC_DIR="$SC_ROOT/etc/descriptions"
mkdir -p "$DESC_DIR"
cp "$SCRIPT_DIR/share/descriptions/scphasepapy.xml" "$DESC_DIR/scphasepapy.xml"
echo "    Installed $DESC_DIR/scphasepapy.xml"

echo
echo "==> Installing default configuration ..."
DEFAULTS_DIR="$SC_ROOT/etc/defaults"
mkdir -p "$DEFAULTS_DIR"
cp "$SCRIPT_DIR/share/defaults/scphasepapy.cfg" "$DEFAULTS_DIR/scphasepapy.cfg"
echo "    Installed $DEFAULTS_DIR/scphasepapy.cfg"

# 5. User config file
USER_CFG="$SC_ROOT/etc/scphasepapy.cfg"
if [[ ! -f "$USER_CFG" ]]; then
    echo
    echo "==> Creating initial user config at $USER_CFG ..."
    cat > "$USER_CFG" <<'CFGEOF'
# scphasepapy user configuration (overrides defaults)
# See /etc/defaults/scphasepapy.cfg for defaults.

# phasepapy.db_dir = /tmp/scphasepapy
# phasepapy.db_assoc = assoc.db
# phasepapy.db_tt = tt.db
# phasepapy.max_km = 350
# phasepapy.aggregation = 1
# phasepapy.aggr_norm = L2
# phasepapy.assoc_ot_uncert = 3
# phasepapy.nsta_declare = 3
# phasepapy.cutoff_outlier = 30
# phasepapy.loc_uncert_thresh = 0.2
# phasepapy.cycle_seconds = 30
# phasepapy.max_pick_age = 3600
CFGEOF
    echo "    Created $USER_CFG"
else
    echo "    User config already exists at $USER_CFG (not overwritten)"
fi

# 6. Optional runtime directories
SPOOL_ROOT="/var/spool/scphasepapy"
if ! mkdir -p "$SPOOL_ROOT" 2>/dev/null; then
    SPOOL_ROOT="$HOME/scphasepapy/spool"
    echo "    /var/spool not writable; using $SPOOL_ROOT"
fi
for D in "$SPOOL_ROOT/picks" "$SPOOL_ROOT/jobs"; do
    mkdir -p "$D" && echo "    $D" || echo "    WARNING: could not create $D"
done

echo
echo "================================================================"
echo "scphasepapy installed successfully."
echo
echo "Next steps:"
echo "  1. Edit $USER_CFG"
echo "  2. seiscomp enable scphasepapy"
echo "  3. seiscomp update-config scphasepapy"
echo "  4. seiscomp start scphasepapy"
echo
