#!/usr/bin/env bash
# install.sh – install sceasyquake into a SeisComP environment
#
# Usage:
#   ./install.sh [SEISCOMP_ROOT]
#
# If SEISCOMP_ROOT is not given, the script tries:
#   1. $SEISCOMP_ROOT environment variable
#   2. ~/seiscomp (common default)
#
# After installation:
#   seiscomp enable sceasyquake
#   seiscomp update-config sceasyquake
#   seiscomp start sceasyquake
#
# To configure streams / model open scconfig and find sceasyquake under
# the Processing category, or edit $SEISCOMP_ROOT/etc/sceasyquake.cfg
# directly.

set -euo pipefail

# ---------------------------------------------------------------------------
# Locate SeisComP root
# ---------------------------------------------------------------------------
SC_ROOT="${1:-${SEISCOMP_ROOT:-$HOME/seiscomp}}"
if [[ ! -d "$SC_ROOT" ]]; then
    echo "ERROR: SeisComP root '$SC_ROOT' not found."
    echo "       Pass the path as the first argument: $0 /path/to/seiscomp"
    exit 1
fi
echo "Using SeisComP root: $SC_ROOT"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ---------------------------------------------------------------------------
# 1. Install the Python library so `import sceasyquake` works from
#    seiscomp-python.  We use pip's --user install if we don't have write
#    access to the system site-packages.
# ---------------------------------------------------------------------------
echo
echo "==> Installing sceasyquake Python package ..."

# Resolve the Python interpreter that SeisComP uses.
# Priority:
#   1. $SC_PYTHON env var (set by user following the install docs)
#   2. $SC_ROOT/bin/seiscomp-python (standard SeisComP wrapper)
#   3. seiscomp-python on PATH
#   4. python3 on PATH (last resort)
if [[ -n "${SC_PYTHON:-}" && -x "$SC_PYTHON" ]]; then
    SC_PY="$SC_PYTHON"
    echo "    Using SC_PYTHON env var: $SC_PY"
elif [[ -x "$SC_ROOT/bin/seiscomp-python" ]]; then
    SC_PY="$SC_ROOT/bin/seiscomp-python"
elif command -v seiscomp-python &>/dev/null; then
    SC_PY="$(command -v seiscomp-python)"
else
    SC_PY="$(command -v python3)"
    echo "    WARNING: seiscomp-python not found; using $SC_PY"
    echo "    If 'import seiscomp' fails, set SC_PYTHON and re-run."
fi
echo "    Python: $SC_PY"

if "$SC_PY" -m pip --version &>/dev/null; then
    "$SC_PY" -m pip install --quiet -e "$SCRIPT_DIR" && \
        echo "    Package installed (editable)" || \
        echo "    WARNING: pip install failed – run manually: $SC_PY -m pip install -e $SCRIPT_DIR"
else
    echo "    WARNING: pip not available for $SC_PY"
    echo "    Run manually: $SC_PY -m pip install -e $SCRIPT_DIR"
fi

# ---------------------------------------------------------------------------
# 2. Install the executable (bin/sceasyquake)
# ---------------------------------------------------------------------------
echo
echo "==> Installing executable to $SC_ROOT/bin/sceasyquake ..."

# Build a wrapper with the correct seiscomp-python shebang
BIN_DEST="$SC_ROOT/bin/sceasyquake"

# Use Python to write the file cleanly (avoids terminal escape code contamination
# that can happen with shell heredoc redirects inside some terminal emulators)
python3 - "$SCRIPT_DIR/bin/sceasyquake-stream.py" "$BIN_DEST" <<'PYEOF'
import sys
src_path, dst_path = sys.argv[1], sys.argv[2]
with open(src_path) as f:
    lines = f.read().split('\n')
if lines[0].startswith('#!'):
    lines[0] = '#!/usr/bin/env seiscomp-python'
lines.insert(1, '# AUTO-GENERATED by sceasyquake/install.sh – edit source in sceasyquake/bin/sceasyquake-stream.py')
with open(dst_path, 'w') as f:
    f.write('\n'.join(lines))
print(f'Written {dst_path}')
PYEOF
chmod 755 "$BIN_DEST"
echo "    Installed $BIN_DEST"

# ---------------------------------------------------------------------------
# 3. Install the module description (for scconfig)
# ---------------------------------------------------------------------------
echo
echo "==> Installing module description ..."
DESC_DIR="$SC_ROOT/etc/descriptions"
mkdir -p "$DESC_DIR"
cp "$SCRIPT_DIR/share/descriptions/sceasyquake.xml" "$DESC_DIR/sceasyquake.xml"
echo "    Installed $DESC_DIR/sceasyquake.xml"

# ---------------------------------------------------------------------------
# 4. Install the default configuration
# ---------------------------------------------------------------------------
echo
echo "==> Installing default configuration ..."
DEFAULTS_DIR="$SC_ROOT/etc/defaults"
mkdir -p "$DEFAULTS_DIR"
cp "$SCRIPT_DIR/share/defaults/sceasyquake.cfg" "$DEFAULTS_DIR/sceasyquake.cfg"
echo "    Installed $DEFAULTS_DIR/sceasyquake.cfg"

# ---------------------------------------------------------------------------# 5b. Symlink the Python package into SeisComP's lib/python so that
#     seiscomp-python (which uses system Python, not anaconda) can find it.
# ---------------------------------------------------------------------------
echo
echo "==> Symlinking Python package into $SC_ROOT/lib/python ..."
SC_PY_LIB="$SC_ROOT/lib/python"
mkdir -p "$SC_PY_LIB"
ln -sfn "$SCRIPT_DIR/lib/sceasyquake" "$SC_PY_LIB/sceasyquake"
echo "    Linked $SC_PY_LIB/sceasyquake -> $SCRIPT_DIR/lib/sceasyquake"

# ---------------------------------------------------------------------------# 5. Create a user-editable config if none exists yet
# ---------------------------------------------------------------------------
USER_CFG="$SC_ROOT/etc/sceasyquake.cfg"
if [[ ! -f "$USER_CFG" ]]; then
    echo
    echo "==> Creating initial user config at $USER_CFG ..."
    cat > "$USER_CFG" <<'CFGEOF'
# sceasyquake configuration
# Edit here or use scconfig (Processing → sceasyquake)
#
# Uncomment and adjust the streams you want to pick:
# streams.codes = CI.*.*.HHZ,CI.*.*.EHZ
#
# For GPU inference:
# picker.device = cuda
#
# Pick probability threshold:
# picker.threshold = 0.5
#
# See $SEISCOMP_ROOT/etc/defaults/sceasyquake.cfg for all available parameters.
CFGEOF
    echo "    Created $USER_CFG"
else
    echo "    User config already exists at $USER_CFG (not overwritten)"
fi

# ---------------------------------------------------------------------------
# 6. Create runtime directories
# ---------------------------------------------------------------------------
echo
echo "==> Creating runtime directories ..."
# Try /var/spool first; fall back to $HOME/sceasyquake/spool
SPOOL_ROOT="/var/spool/sceasyquake"
if ! mkdir -p "$SPOOL_ROOT" 2>/dev/null; then
    SPOOL_ROOT="$HOME/sceasyquake/spool"
    echo "    /var/spool not writable; using $SPOOL_ROOT"
fi
for D in "$SPOOL_ROOT/picks" "$SPOOL_ROOT/jobs"; do
    mkdir -p "$D" && echo "    $D" || \
        echo "    WARNING: could not create $D"
done
echo "    Pick YAML fallback directory: $SPOOL_ROOT/picks"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
echo
echo "================================================================"
echo "sceasyquake installed successfully."
echo
echo "Next steps:"
echo "  1. Edit $USER_CFG"
echo "     (or open scconfig → Processing → sceasyquake)"
echo "  2. seiscomp enable sceasyquake"
echo "  3. seiscomp update-config sceasyquake"
echo "  4. seiscomp start sceasyquake"
echo
echo "To verify picks are flowing:"
echo "  scmv  (or)  scamp --print-picks -H localhost"
echo "================================================================"
