#!/usr/bin/env bash
# install.sh – install scpyocto into a SeisComP environment
#
# Usage:
#   ./install.sh [SEISCOMP_ROOT]
#
# If SEISCOMP_ROOT is not given, the script tries:
#   1. $SEISCOMP_ROOT environment variable
#   2. ~/seiscomp (common default)
#
# After installation:
#   seiscomp enable scpyocto
#   seiscomp update-config scpyocto
#   seiscomp start scpyocto

set -euo pipefail

SC_ROOT="${1:-${SEISCOMP_ROOT:-$HOME/seiscomp}}"
if [[ ! -d "$SC_ROOT" ]]; then
    echo "ERROR: SeisComP root '$SC_ROOT' not found."
    echo "       Pass the path as the first argument: $0 /path/to/seiscomp"
    exit 1
fi
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Using SeisComP root: $SC_ROOT"

echo
echo "==> Installing scpyocto Python package ..."

if [[ -n "${SC_PYTHON:-}" && -x "$SC_PYTHON" ]]; then
    SC_P="$SC_PYTHON"
    echo "    Using SC_PYTHON env var: $SC_P"
elif [[ -x "$SC_ROOT/bin/seiscomp-python" ]]; then
    SC_P="$SC_ROOT/bin/seiscomp-python"
elif command -v seiscomp-python &>/dev/null; then
    SC_P="$(command -v seiscomp-python)"
else
    SC_P="$(command -v python3)"
    echo "    WARNING: seiscomp-python not found; using $SC_P"
    echo "    If 'import seiscomp' fails, set SC_PYTHON and re-run."
fi
echo "    Python: $SC_P"

if "$SC_P" -m pip --version &>/dev/null; then
    "$SC_P" -m pip install --quiet -e "$SCRIPT_DIR" && \
        echo "    Package installed (editable)" || \
        echo "    WARNING: pip install failed – run manually: $SC_P -m pip install -e $SCRIPT_DIR"
else
    echo "    WARNING: pip not available for $SC_P"
    echo "    Run manually: $SC_P -m pip install -e $SCRIPT_DIR"
fi

echo
echo "==> Installing executable to $SC_ROOT/bin/scpyocto ..."
BIN_DEST="$SC_ROOT/bin/scpyocto"
python3 - "$SCRIPT_DIR/lib/scpyocto/scpyocto.py" "$BIN_DEST" <<'PYEOF'
import sys
src_path, dst_path = sys.argv[1], sys.argv[2]
with open(src_path) as f:
    lines = f.read().split('\n')
if lines[0].startswith('#!'):
    lines[0] = '#!/usr/bin/env seiscomp-python'
lines.insert(1, '# AUTO-GENERATED by scpyocto/install.sh – edit source in scpyocto/lib/scpyocto/scpyocto.py')
with open(dst_path, 'w') as f:
    f.write('\n'.join(lines))
print(f'Written {dst_path}')
PYEOF
chmod 755 "$BIN_DEST"
echo "    Installed $BIN_DEST"

echo
echo "==> Installing module description ..."
DESC_DIR="$SC_ROOT/etc/descriptions"
mkdir -p "$DESC_DIR"
cp "$SCRIPT_DIR/share/descriptions/scpyocto.xml" "$DESC_DIR/scpyocto.xml"
echo "    Installed $DESC_DIR/scpyocto.xml"

echo
echo "==> Installing default configuration ..."
DEFAULTS_DIR="$SC_ROOT/etc/defaults"
mkdir -p "$DEFAULTS_DIR"
cp "$SCRIPT_DIR/share/defaults/scpyocto.cfg" "$DEFAULTS_DIR/scpyocto.cfg"
echo "    Installed $DEFAULTS_DIR/scpyocto.cfg"

echo
echo "==> Installing init script ..."
INIT_DIR="$SC_ROOT/etc/init"
mkdir -p "$INIT_DIR"
cat > "$INIT_DIR/scpyocto.py" <<'INITEOF'
import seiscomp.kernel

class Module(seiscomp.kernel.Module):
    def __init__(self, env):
        seiscomp.kernel.Module.__init__(self, env, env.moduleName(__file__))
INITEOF
echo "    Installed $INIT_DIR/scpyocto.py"

USER_CFG="$SC_ROOT/etc/scpyocto.cfg"
if [[ ! -f "$USER_CFG" ]]; then
    echo
    echo "==> Creating initial user config at $USER_CFG ..."
    cat > "$USER_CFG" <<'CFGEOF'
# scpyocto user configuration
# See etc/defaults/scpyocto.cfg for all parameters and their defaults.
# Uncomment and edit to override defaults for your network.

# pyocto.lat_min = 28.0
# pyocto.lat_max = 38.0
# pyocto.lon_min = -107.0
# pyocto.lon_max = -93.0
# pyocto.depth_min = 0.0
# pyocto.depth_max = 50.0
# pyocto.vp = 6.0
# pyocto.vs = 3.46
# pyocto.tolerance = 2.0
# pyocto.time_before = 300.0
# pyocto.n_picks = 6
# pyocto.n_p_picks = 3
# pyocto.n_s_picks = 0
# pyocto.n_p_and_s_picks = 3
# pyocto.pick_match_tolerance = 2.0
# pyocto.min_interevent_time = 3.0
# pyocto.time_slicing = 1200.0
# pyocto.cycle_seconds = 30
# pyocto.max_pick_age = 1800
CFGEOF
    echo "    Created $USER_CFG"
else
    echo "    User config already exists at $USER_CFG (not overwritten)"
fi

echo
echo "================================================================"
echo "scpyocto installed successfully."
echo
echo "Next steps:"
echo "  1. Edit $USER_CFG to set your bounding box and velocity model"
echo "  2. seiscomp enable scpyocto"
echo "  3. seiscomp update-config scpyocto"
echo "  4. seiscomp start scpyocto"
echo
