# sceasyquake config (example)

[general]
job_dir = /var/spool/sceasyquake/jobs
# mode: 'continuous' (default) or 'event'
mode = continuous
# easyQuake machine picker name (GPD, EQTransformer, PhaseNet)
machine_picker = GPD

[seiscomp]
# If you want the client to subscribe to messaging, set these; otherwise you can
# write job YAML files into job_dir by other means
messaging = True
subscribe = origin,pick

[worker]
# python executable / conda env command or empty to use system python
python_cmd = python
# Check interval for jobs (seconds)
check_interval = 5
